import {
  Accessibility,
  AudioLines,
  AudioWaveform,
  Award,
  BadgeCheck,
  BookMarked,
  BookOpen,
  Bot,
  BrainCircuit,
  Brush,
  Building2,
  CalendarCheck,
  CalendarDays,
  CalendarRange,
  ClipboardCheck,
  Clapperboard,
  Code2,
  Cog,
  Compass,
  Cpu,
  Database,
  Disc3,
  Drama,
  Drum,
  Earth,
  FileCheck,
  FileCode,
  FileMusic,
  FileText,
  Gamepad2,
  Globe,
  GraduationCap,
  Guitar,
  Handshake,
  Headphones,
  HeartHandshake,
  History,
  Landmark,
  Languages,
  Laptop,
  Layers,
  Library,
  Lightbulb,
  ListMusic,
  Map,
  MapPin,
  Megaphone,
  Mic,
  MicVocal,
  Microscope,
  MonitorPlay,
  MousePointerClick,
  Music,
  Music2,
  Music4,
  Network,
  Newspaper,
  Palette,
  PenTool,
  Piano,
  Podcast,
  Presentation,
  Puzzle,
  Radio,
  Rocket,
  School,
  ScrollText,
  Share2,
  ShieldCheck,
  Sparkles,
  Speaker,
  Sprout,
  Target,
  Telescope,
  Theater,
  Trophy,
  Users,
  UsersRound,
  Video,
  Wand2,
  Waves,
  type LucideIcon,
} from "lucide-react";

/**
 * Iconos disponibles para las listas editables del gestor (nombre Lucide en
 * kebab-case → componente). Si en el panel se escribe un nombre desconocido,
 * se usa Sparkles como comodín en vez de romper la página.
 *
 * Además de los generales heredados de la web del IUCE, incluye los del
 * ámbito de DIDEROT: música, sonido, artes escénicas y humanidades digitales.
 */
export const ICONS: Record<string, LucideIcon> = {
  accessibility: Accessibility,
  "audio-lines": AudioLines,
  "audio-waveform": AudioWaveform,
  award: Award,
  "badge-check": BadgeCheck,
  "book-marked": BookMarked,
  "book-open": BookOpen,
  bot: Bot,
  "brain-circuit": BrainCircuit,
  brush: Brush,
  "building-2": Building2,
  "calendar-check": CalendarCheck,
  "calendar-days": CalendarDays,
  "calendar-range": CalendarRange,
  clapperboard: Clapperboard,
  "clipboard-check": ClipboardCheck,
  "code-2": Code2,
  cog: Cog,
  compass: Compass,
  cpu: Cpu,
  database: Database,
  "disc-3": Disc3,
  drama: Drama,
  drum: Drum,
  earth: Earth,
  "file-check": FileCheck,
  "file-code": FileCode,
  "file-music": FileMusic,
  "file-text": FileText,
  "gamepad-2": Gamepad2,
  globe: Globe,
  "graduation-cap": GraduationCap,
  guitar: Guitar,
  handshake: Handshake,
  headphones: Headphones,
  "heart-handshake": HeartHandshake,
  history: History,
  landmark: Landmark,
  languages: Languages,
  laptop: Laptop,
  layers: Layers,
  library: Library,
  lightbulb: Lightbulb,
  "list-music": ListMusic,
  map: Map,
  "map-pin": MapPin,
  megaphone: Megaphone,
  mic: Mic,
  "mic-vocal": MicVocal,
  microscope: Microscope,
  "monitor-play": MonitorPlay,
  "mouse-pointer-click": MousePointerClick,
  music: Music,
  "music-2": Music2,
  "music-4": Music4,
  network: Network,
  newspaper: Newspaper,
  palette: Palette,
  "pen-tool": PenTool,
  piano: Piano,
  podcast: Podcast,
  presentation: Presentation,
  puzzle: Puzzle,
  radio: Radio,
  rocket: Rocket,
  school: School,
  "scroll-text": ScrollText,
  "share-2": Share2,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  speaker: Speaker,
  sprout: Sprout,
  target: Target,
  telescope: Telescope,
  theater: Theater,
  trophy: Trophy,
  users: Users,
  "users-round": UsersRound,
  video: Video,
  "wand-2": Wand2,
  waves: Waves,
};

export const ICON_NAMES = Object.keys(ICONS).sort();

export function iconFor(name: string | boolean | undefined): LucideIcon {
  if (typeof name === "string" && ICONS[name]) return ICONS[name];
  return Sparkles;
}
